---
daemonset:
  extraEnvs:
    - name: ELASTICSEARCH_HOST
      value: https://elasticsearch-es-http
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: ELASTICSEARCH_USERNAME
      value: elastic
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: elastic
          name: elasticsearch-es-elastic-user
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.autodiscover:
        providers:
        - hints:
            default_config: {}
            enabled: "true"
          host: ${NODE_NAME}
          type: kubernetes
      metricbeat.modules:
      - module: kubernetes
        metricsets:
          - container
          - node
          - pod
          - system
          - volume
        period: 10s
        host: "${NODE_NAME}"
        hosts: ["https://${NODE_NAME}:10250"]
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl.verification_mode: "none"
        processors:
        - add_kubernetes_metadata: {}
        - add_cloud_metadata: {}
        - add_host_metadata: {}
      - module: kubernetes
        enabled: true
        metricsets:
          - event
      - module: system
        period: 10s
        metricsets:
          - cpu
          - load
          - memory
          - network
          - diskio
          - process
          - process_summary
        processes: ['.*']
        process.include_top_n:
          by_cpu: 5
          by_memory: 5
      - module: system
        period: 1m
        metricsets:
          - filesystem
          - fsstat
        processors:
        - drop_event.when.regexp:
            system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
      output.elasticsearch:
        hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        ssl.verification_mode: none
deployment:
  extraEnvs: 
    - name: ELASTICSEARCH_HOST
      value: https://elasticsearch-es-http
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: ELASTICSEARCH_USERNAME
      value: elastic
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: elastic
          name: elasticsearch-es-elastic-user
    - name: KIBANA_HOST
      value: https://gvms-kibana-kb-http
    - name: KIBANA_PORT
      value: "5601"
    - name: AWS_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: rdskey
          name: aws-access-key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: rdssecretkey
          name: aws-access-key
    - name: HTTPS_PROXY
      value: "http://10.41.199.134:9090"
    - name: no_proxy
      value: '169.254.169.254,.eu-west-2.eks.amazonaws.com,.eu-west-2.sts.amazonaws.com,.s3.amazonaws.com,.corp.hmrc.gov.uk,172.20.0.1:443,rds.eu-west-2.amazonaws.com,elasticsearch-es-http:9200'
  metricbeatConfig:
    metricbeat.yml: |
      metricbeat.modules:
      - module: kubernetes
        enabled: true
        metricsets:
          - state_node
          - state_deployment
          - state_replicaset
          - state_statefulset
          - state_pod
          - state_container
          - state_cronjob
          - state_resourcequota
          - state_service
          - state_persistentvolume
          - state_persistentvolumeclaim
          - state_storageclass
        period: 10s
        hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
      - module: aws
        period: 60s
        metricsets:
          - rds
        regions:
          - eu-west-2
        access_key_id: '${AWS_ACCESS_KEY}'
        secret_access_key: '${AWS_SECRET_ACCESS_KEY}'
      - module: aws
        period: 60s
        enabled: true
        metricsets:
          - cloudwatch
        metrics:
          - namespace: AWS/DMS
        regions:
          - eu-west-2
        access_key_id: '${AWS_ACCESS_KEY}'
        secret_access_key: '${AWS_SECRET_ACCESS_KEY}'    
      output.elasticsearch:
        hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        ssl.verification_mode: none
      setup.kibana:
        host: ${KIBANA_HOST:kibana}:${KIBANA_PORT:5601}
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        ssl.verification_mode: none
      setup.dashboards.enabled: true
image: "gvms-roro-docker-all-virtual.artifactory.alm.corp.hmrc.gov.uk/gvms-tool/elastic/metricbeat"
imageTag: "7.10.0"
imagePullPolicy: "Always"
